services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
      - "33060:33060"
